/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const store_Reorder_Logic = require('./code/store-reorder-logic');

class inventoryManagementSrv extends LCAPApplicationService {
    async init() {

        this.on('READ', 'Store', async (request, next) => {
            await store_Reorder_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    inventoryManagementSrv
};